### ISSUE TITLE
cash

### ISSUE THREAD

**Issue by Natsukiw** [Unknown025/Flans-Mod-Plus#5]
https://cdn.discordapp.com/attachments/436132134428737537/720927199838076938/cash.png

java.lang.ClassCastException: net.minecraft.item.ItemArmor cannot be cast to com.flansmod.common.teams.ItemTeamArmour
	at com.flansmod.common.guns.raytracing.PlayerHitbox.hitByBullet(PlayerHitbox.java:155)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:573)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2005)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:972)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.guns.raytracing.PlayerHitbox.hitByBullet(PlayerHitbox.java:155)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:573)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: Bullet (com.flansmod.common.guns.EntityBullet)
	Entity ID: 25828
	Entity Name: entity.Bullet.name
	Entity's Exact location: 1208.44, 64.59, 242.44
	Entity's Block location: World: (1208,64,242), Chunk: (at 8,4,2 in 75,15; contains blocks 1200,0,240 to 1215,255,255), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 10.15, -0.63, 10.87
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

**Comment by Unknown025** [comment]
Interesting, I'll look into this.

**Comment by Unknown025** [comment]
Should be resolved in the latest commit now, I'll close this when I get the chance to verify it.

**Comment by Unknown025** [comment]
Fixed in the latest release.
