### ISSUE TITLE
A problem with gunboxes and their configs and items from other mods after updating to version 1.48

### ISSUE THREAD

**Issue by AHAPXNCT** [Unknown025/Flans-Mod-Plus#58]
Good afternoon. There was a problem with gunboxes and their configs after updating to version 1.48. I have implemented crafting of weapons in boxes and armor using items from the CustomNPC mod. In fact, on the server, the store consists of boxes in which weapons from all flans packs. And its purchase takes place for items and coins from the Custom NPC. After the update, coins disappeared in the boxes, only the weapons in which vanilla resources participate are available, and everything that was from the CustomNPC crafting crashes and knocks out such an error into the console ...

https://pastebin.com/WBgBfUv3

`[09:38:40] [AutoSaveWorld AutoSaveThread/INFO]: [0;31;1mВыполняеться сохранение мира...[m
[09:38:40] [AutoSaveWorld AutoSaveThread/INFO]: [0;32;22mМир успешно сохранился![m
[09:39:39] [Server thread/ERROR]: There was a critical exception handling a packet on channel FlansMod
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.58]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at com.flansmod.common.guns.boxes.BlockGunBox.buyGun(BlockGunBox.java:55) ~[BlockGunBox.class:?]
	at com.flansmod.common.network.PacketBuyWeapon.handleServerSide(PacketBuyWeapon.java:47) ~[PacketBuyWeapon.class:?]
	at com.flansmod.common.network.PacketHandler.decode(PacketHandler.java:114) ~[PacketHandler.class:?]
	at com.flansmod.common.network.PacketHandler.decode(PacketHandler.java:39) ~[PacketHandler.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 13 more
[09:39:39] [Server thread/INFO]: Test lost connection: A fatal error has occured, this connection is terminated`

In all previous versions, this all worked correctly for several years now. Namely, in version 1.48, something has changed, and now items from another mod are not visible in the weapon boxes.

client logs:
`[09:38:56] [Client thread/INFO] [Flan's Mod Ultimate]: Loaded textures and models.
[09:39:04] [Client thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeline:12]: [Dragon's Radio Mod] Stopping all currently running radio streams.
[09:39:04] [Client thread/INFO] [FML]: Applying holder lookups
[09:39:04] [Client thread/INFO] [FML]: Holder lookups applied
[09:39:11] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_211]
	at pro.gravit.launcher.kRAftOKTks8liY.kRAfToktKfVKBc(Unknown Source) [KraftOK.exe:?]
	at pro.gravit.launcher.kRAftOKTks8liY.main(Unknown Source) [KraftOK.exe:?]
Caused by: java.lang.NullPointerException
	at com.flansmod.common.guns.boxes.BlockGunBox.buyGun(BlockGunBox.java:55) ~[BlockGunBox.class:?]
	at com.flansmod.client.gui.GuiGunBox.func_73864_a(GuiGunBox.java:367) ~[GuiGunBox.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
	at com.flansmod.client.gui.GuiGunBox.func_146274_d(GuiGunBox.java:222) ~[GuiGunBox.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
	... 12 more
[09:39:12] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/30/21 9:39 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.flansmod.common.guns.boxes.BlockGunBox.buyGun(BlockGunBox.java:55)
	at com.flansmod.client.gui.GuiGunBox.func_73864_a(GuiGunBox.java:367)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at com.flansmod.client.gui.GuiGunBox.func_146274_d(GuiGunBox.java:222)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.kRAftOKTks8liY.kRAfToktKfVKBc(Unknown Source)
	at pro.gravit.launcher.kRAftOKTks8liY.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.guns.boxes.BlockGunBox.buyGun(BlockGunBox.java:55)
	at com.flansmod.client.gui.GuiGunBox.func_73864_a(GuiGunBox.java:367)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at com.flansmod.client.gui.GuiGunBox.func_146274_d(GuiGunBox.java:222)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

-- Affected screen --
Details:
	Screen name: com.flansmod.client.gui.GuiGunBox

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Test'/448075, l='MpServer', x=-1052.21, y=75.62, z=-3463.93], MCH_ViewEntityDummy['McHeliDummyEntity'/38, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 04 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (4271,119,124), Chunk: (at 15,7,12 in 266,7; contains blocks 4256,0,112 to 4271,255,127), Region: (8,0; contains chunks 256,0 to 287,31, blocks 4096,0,0 to 4607,255,511)
	Level time: 1882247336 game time, 1884216018 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 64 total; [EntityCustomNpc['MusicBox'/448262, l='MpServer', x=-1053.50, y=65.00, z=-3469.50], EntityCustomNpc['Всякое разное'/448270, l='MpServer', x=-1047.50, y=79.00, z=-3467.50], EntityCustomNpc['Истребители'/448268, l='MpServer', x=-1047.50, y=79.00, z=-3464.50], EntityCustomNpc['Армопластины'/448266, l='MpServer', x=-1051.50, y=73.00, z=-3459.50], EntityCustomNpc['РЕСУРСЫ I'/448264, l='MpServer', x=-1050.50, y=73.00, z=-3459.50], EntityCustomNpc['Книжный барыга'/448278, l='MpServer', x=-1050.50, y=73.00, z=-3463.50], EntityCustomNpc['Воин'/448279, l='MpServer', x=-1052.50, y=73.00, z=-3465.50], EntityCustomNpc['Продавец ресурсов'/448277, l='MpServer', x=-1054.50, y=73.00, z=-3459.50], EntityCustomNpc['Куплю КУПОНЫ'/448274, l='MpServer', x=-1049.50, y=73.00, z=-3468.50], EntityCustomNpc['Книги'/448275, l='MpServer', x=-1049.50, y=73.00, z=-3463.50], EntityCustomNpc['MCHELI I ТЮРЕЛИ'/448272, l='MpServer', x=-1047.38, y=79.00, z=-3470.34], EntityCustomNpc['Десантные и обычные самолеты'/448286, l='MpServer', x=-1050.50, y=79.00, z=-3468.50], EntityCustomNpc['Танки и БМП'/448284, l='MpServer', x=-1050.50, y=79.00, z=-3465.50], EntityCustomNpc['Дроны и мишени'/448282, l='MpServer', x=-1053.59, y=79.00, z=-3465.50], EntityCustomNpc['Ресурсы II'/448280, l='MpServer', x=-1055.50, y=73.00, z=-3459.50], EntityCustomNpc['Пист.пулеметы'/448294, l='MpServer', x=-1046.50, y=73.00, z=-3479.50], EntityCustomNpc['Дробовики'/448292, l='MpServer', x=-1044.38, y=73.00, z=-3479.63], EntityCustomNpc['Buildcraft скупщик'/448290, l='MpServer', x=-1055.50, y=73.00, z=-3467.50], EntityClientPlayerMP['Test'/448075, l='MpServer', x=-1052.21, y=75.62, z=-3463.93], EntityCustomNpc['Куплю КУПОНЫ II'/448291, l='MpServer', x=-1050.50, y=73.00, z=-3470.50], EntityDruid['Гнилой скелет'/448803, l='MpServer', x=-1098.50, y=31.00, z=-3489.38], MCH_ViewEntityDummy['McHeliDummyEntity'/38, l='MpServer', x=0.00, y=-4.00, z=0.00], EntityCustomNpc['Ударные самолеты и бомбардировщики'/448288, l='MpServer', x=-1050.50, y=79.00, z=-3471.50], EntityCustomNpc['Тяжелое'/448302, l='MpServer', x=-1044.50, y=73.00, z=-3475.50], EntityCustomNpc['Автоматы'/448300, l='MpServer', x=-1044.50, y=73.00, z=-3477.50], EntityCustomNpc['Стац.Пулеметы'/448298, l='MpServer', x=-1046.50, y=73.00, z=-3475.50], EntityCustomNpc['Снайп.Винтовки'/448296, l='MpServer', x=-1048.50, y=73.00, z=-3477.50], EntityCustomNpc['Мелкий обменник валюты'/448310, l='MpServer', x=-1054.50, y=73.00, z=-3480.50], EntityCustomNpc['Винтовки'/448311, l='MpServer', x=-1046.50, y=73.00, z=-3477.50], EntityCustomNpc['Флот'/448308, l='MpServer', x=-1047.38, y=79.00, z=-3473.34], EntityCustomNpc['Взрывчатка'/448306, l='MpServer', x=-1050.50, y=73.00, z=-3475.50], EntityCustomNpc['Пулеметы'/448304, l='MpServer', x=-1048.50, y=73.00, z=-3475.50], EntityItemFrame['entity.ItemFrame.name'/448319, l='MpServer', x=-1047.94, y=79.50, z=-3552.50], EntityCustomNpc['Пистолеты'/448316, l='MpServer', x=-1048.50, y=73.00, z=-3479.50], EntityItemFrame['entity.ItemFrame.name'/448186, l='MpServer', x=-1006.50, y=79.50, z=-3532.06], EntityCustomNpc['Ловушки'/448314, l='MpServer', x=-1050.50, y=73.00, z=-3477.50], EntityCaveSpider['Пещерный паук'/1981, l='MpServer', x=-4.28, y=-38.15, z=-50.64], EntityItemFrame['entity.ItemFrame.name'/448187, l='MpServer', x=-1007.50, y=79.50, z=-3532.06], EntityItemFrame['entity.ItemFrame.name'/448185, l='MpServer', x=-1005.50, y=79.50, z=-3532.06], EntityCustomNpc['Крупный обменник валюты'/448313, l='MpServer', x=-1052.50, y=73.00, z=-3480.50], EntityCustomNpc['MusicBox'/448198, l='MpServer', x=-1021.50, y=69.00, z=-3517.50], EntityItemFrame['entity.ItemFrame.name'/448320, l='MpServer', x=-1047.94, y=79.50, z=-3553.50], EntityItemFrame['entity.ItemFrame.name'/448321, l='MpServer', x=-1047.94, y=79.50, z=-3554.50], EntityCustomNpc['Торговец инструментом'/448335, l='MpServer', x=-1061.50, y=73.00, z=-3464.50], EntityCustomNpc['Авиация'/448333, l='MpServer', x=-1061.50, y=73.00, z=-3465.50], EntityCustomNpc['Запчасти II'/448331, l='MpServer', x=-1061.50, y=73.00, z=-3470.50], EntityCustomNpc['Роботы'/448329, l='MpServer', x=-1060.50, y=73.00, z=-3467.50], EntityCustomNpc['Автотранспорт'/448342, l='MpServer', x=-1056.50, y=79.00, z=-3465.50], EntityCustomNpc['Торговец красителями'/448341, l='MpServer', x=-1057.50, y=73.00, z=-3459.50], EntityCustomNpc['Запчасти III'/448339, l='MpServer', x=-1060.50, y=73.00, z=-3471.50], EntityCustomNpc['Торговец оружием'/448336, l='MpServer', x=-1061.69, y=73.00, z=-3462.59], EntityCustomNpc['Запчасти'/448337, l='MpServer', x=-1060.50, y=73.00, z=-3469.50], EntityCustomNpc['Терпила'/448350, l='MpServer', x=-1056.50, y=73.00, z=-3481.50], EntityTrail['неизвестно'/474, l='MpServer', x=-1052.21, y=75.62, z=-3463.93], EntityCustomNpc['Транспортные вертолеты'/448348, l='MpServer', x=-1056.50, y=79.00, z=-3474.50], EntityCustomNpc['Многоцелевые вертолеты'/448346, l='MpServer', x=-1056.50, y=79.00, z=-3471.50], EntityCustomNpc['Ударные вертолеты'/448344, l='MpServer', x=-1056.50, y=79.00, z=-3468.50], EntityCustomNpc['Торговец оружием'/448352, l='MpServer', x=-1060.50, y=73.00, z=-3473.50], EntitySquid['Спрут'/448750, l='MpServer', x=-1092.50, y=55.88, z=-3459.44], EntitySquid['Спрут'/448758, l='MpServer', x=-1112.66, y=54.78, z=-3448.31], EntitySquid['Спрут'/448756, l='MpServer', x=-1102.03, y=56.56, z=-3444.97], EntitySquid['Спрут'/448757, l='MpServer', x=-1102.91, y=54.69, z=-3447.75], EntitySquid['Спрут'/448755, l='MpServer', x=-1106.72, y=56.72, z=-3449.66], EntitySquid['Спрут'/448753, l='MpServer', x=-1106.56, y=57.09, z=-3448.03]]
	Retry entities: 0 total; []
	Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.kRAftOKTks8liY.kRAfToktKfVKBc(Unknown Source)
	at pro.gravit.launcher.kRAftOKTks8liY.main(Unknown Source)
`

**Comment by AHAPXNCT** [comment]
Sorry, the problem has been resolved, and it ended up not in Flans Mod 1.48, but due to this mod https://www.curseforge.com/minecraft/mc-mods/flans-mod-npc-vehicles

Can be closed as resolved

**Comment by Unknown025** [comment]
Glad to hear you figured it out.
