### ISSUE TITLE
Server crash after throwing grenade

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#86]
I was playing with my friends when all of a sudden the server crashed after someone threw a grenade.
I don't know if I was just extremely unlucky or if this is a more common issue but it was certainly not the first grenade we threw. I'll keep investigating when I have the time. Hope this can be resolved quickly ;)

Here is the error:

net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:960) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.7.0_221]
Caused by: java.lang.NullPointerException
	at com.flansmod.common.guns.EntityDamageSourceFlans.func_151519_b(EntityDamageSourceFlans.java:52) ~[EntityDamageSourceFlans.class:?]
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:100) ~[rn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:545) ~[mw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) ~[mw.class:?]
	at com.flansmod.common.guns.FlansModExplosion.func_77278_a(FlansModExplosion.java:206) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.FlansModExplosion.<init>(FlansModExplosion.java:72) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.EntityGrenade.detonate(EntityGrenade.java:521) ~[EntityGrenade.class:?]
	at com.flansmod.common.guns.EntityGrenade.func_70071_h_(EntityGrenade.java:191) ~[EntityGrenade.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2647) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2600) ~[ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2412) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
	... 4 more
>
[14:27:45 ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at com.flansmod.common.guns.EntityDamageSourceFlans.func_151519_b(EntityDamageSourceFlans.java:52) ~[EntityDamageSourceFlans.class:?]
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:100) ~[rn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:545) ~[mw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) ~[mw.class:?]
	at com.flansmod.common.guns.FlansModExplosion.func_77278_a(FlansModExplosion.java:206) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.FlansModExplosion.<init>(FlansModExplosion.java:72) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.EntityGrenade.detonate(EntityGrenade.java:521) ~[EntityGrenade.class:?]
	at com.flansmod.common.guns.EntityGrenade.func_70071_h_(EntityGrenade.java:191) ~[EntityGrenade.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2647) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2600) ~[ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2412) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.7.0_221]
>
[14:27:45 ERROR]: This crash report has been saved to: /mnt/minecraftotherpacks/./crash-reports/crash-2021-11-08_14.27.45-server.txt
>
[14:27:45 INFO]: Stopping server

**Comment by GoldSloth** [comment]
I believe this has been patched already, let me know if it happens after next release.
Thanks for reporting ;)

**Comment by pixelrider2000** [comment]
Awesome but may you send me a version where it's supposedly fixed? Like I said, since I'm playing on a server I don't want it to crash all the time because we are using grenades.

Thanks a lot!

**Comment by GoldSloth** [comment]
The current working version is not very stable at all, I'd reccomend going back to 1.48 until we release another version.
It should only be a few weeks hopefully.
